### ISSUE TITLE
Publish to jcenter

### ISSUE THREAD

**Issue by louis993546** [greenrobot/ObjectBoxRxJava#10]
TL;DR: `implementation 'io.objectbox:objectbox-rxjava:0.9.8'` does not work

Can you guys update it on which version is available? Thanks!

**Comment by greenrobot-team** [comment]
This library has not moved to jcenter (yet), unlike the common ObjectBox libraries. For now add the old repository in your build file:
```
repositories {
    maven { url "http://objectbox.net/beta-repo/" }
}
```
-ut

**Comment by louis993546** [comment]
Yea I still have your beta repo in my gradle file. It is just not picking up.

project `build.gradle`
```
...
repositories {
    google()
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
    maven { url "http://objectbox.net/beta-repo" }
}
...
```

app `build.gradle`
```
...
dependencies {
    ...
    implementation 'io.objectbox:objectbox-rxjava:0.9.8'
    ...
}
```

**Comment by greenrobot-team** [comment]
[`0.9.8` is still there](http://objectbox.net/beta-repo/io/objectbox/objectbox-rxjava/0.9.8/objectbox-rxjava-0.9.8.pom) and we have an internal project that resolves it correctly. Double-check your build files.

edit: note that a VPN or a restricted internet connection (proxy) might have issues. -ut

**Comment by louis993546** [comment]
I turned off VPN but somehow it's still not working. I will look into it.

**Comment by Tooto** [comment]
same problem here

**Comment by rs-georg** [comment]
~~Same here. The dependency cannot be resolved although I added the beta repo in the build.gradle file.~~

My bad. I added the repository at the wrong place. It should not be in the buildscript closure.

```
buildscript {
    repositories {
        google()
        jcenter()
       // do not add it here
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        // this is the correct place
        maven { url "http://objectbox.net/beta-repo/" }
    }
}
```

**Comment by louis993546** [comment]
Confirmed @rs-georg 's solution works (Thanks @rs-georg ), but I am still not using it for now because #9 is still not merged and I really need `Single` to work right now. 

Also it should at least be in `README`

**Comment by vee-zhang** [comment]
same problem here

**Comment by greenrobot-team** [comment]
Completed as a side-effect of #12. Expect a new release as part of the next ObjectBox 2.0.0 beta. -ut
