### ISSUE TITLE
Deleting all entities from a box doesn't emit an item from a reactive query

### ISSUE THREAD

**Issue by maciej-kaznowski** [greenrobot/ObjectBoxRxJava#8]
When I subscribe to an observable such as `RxQuery.observable(box.query().build())` and then delete all entities from the box via `box.removeAll()` then it doesn't emit an empty list of entities.

**Comment by greenrobot-team** [comment]
I created a test case and it works as expected. After `removeAll()` an empty set of results can be observed in `onNext()`.

It would help if you can provide a small example project that reproduces this error. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
